version: '3'

services:

  redis:
    restart: always
    image: redis:latest
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
    command:
      - --maxmemory 256MB
      - --requirepass pass

  postgres:
    restart: always
    image: postgres:13-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_create.go
      POSTGRES_DB: hey
    ports:
      - "5436:5432"

  prometheus:
    restart: always
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    restart: no
    image: grafana/grafana-oss:latest
    ports:
      - "13000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./metrics/grafana:/var/lib/grafana

  app:
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - prometheus
      - grafana
    ports:
      - "4040:4040"
      - "9091:9091"
    environment:
      DB_HOST: postgres
      DB_PASSWORD: db_create.go
      DB_USERNAME: postgres
      DB_PORT: 5432
      PORT: 4040
      DISABLE_METRICS: false
      DB_NAME: hey
      SSL_MODE: disable
      CORES: "5"
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: pass
      SALT: uipads0797Wy
      JWT_SECRET_KEY: pz1xvp44cMoca1dmf9HJfa
      JWT_SECRET_KEY_FOR_LONGLIVE_TOKEN: zp1mvn65cmOca1hgf9HJfa
      JWT_SECRET_KEY_FOR_REFRESH_TOKEN: aD987L3
      MAX_FILE_SIZE: "66060288"
    volumes:
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./metrics
        target: /metrics
      - type: bind
        source: ./static
        target: /static