DROP TABLE IF EXISTS surveys;
DROP INDEX IF EXISTS parent_posts_idx;

DROP TABLE IF EXISTS comments;
DROP INDEX IF EXISTS parent_post_idx;

DROP TABLE IF EXISTS messages;
DROP INDEX IF EXISTS parent_chat_idx;

DROP TABLE IF EXISTS chats;

DROP TABLE IF EXISTS musics;

DROP TABLE IF EXISTS posts;
DROP INDEX IF EXISTS parent_user_idx;

DROP TABLE IF EXISTS users;
